/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventoscientificios.view;

import eventoscientificos.controllers.ListarSubmissoesRetiradasController;
import eventoscientificos.model.Empresa;
import java.awt.Frame;

/**
 *
 * @author Pedro
 */
public class ListarSubmissoesRetiradasUI extends javax.swing.JDialog {

    private Frame framePai;
    private ListarSubmissoesRetiradasController controller;

    /**
     * Creates new form ListarSubmissoesRetiradasUI
     * @param parent
     * @param modal
     * @param empresa
     */
    public ListarSubmissoesRetiradasUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        this.framePai = parent;
        this.controller = new ListarSubmissoesRetiradasController(empresa);
        setResizable(false);
        initComponents();
        getRootPane().setDefaultButton(this.btn_selecionarSubmissivel);
        setLocationRelativeTo(null);
        // Verificar se existem eventos/sessões que aceitem revisões de artigos.
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_selecionarSubmissivel = new javax.swing.JPanel();
        btn_selecionarSubmissivel = new javax.swing.JButton();
        cmb_selecionarSubmissivel = new javax.swing.JComboBox();
        pnl_submissoesRetiradas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_submissoesRetiradas = new javax.swing.JList();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_selecionarSubmissivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o evento/sessão temática onde pretende listar submissões retiradas"));

        btn_selecionarSubmissivel.setText("Selecionar");
        btn_selecionarSubmissivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarSubmissivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_selecionarSubmissivelLayout = new javax.swing.GroupLayout(pnl_selecionarSubmissivel);
        pnl_selecionarSubmissivel.setLayout(pnl_selecionarSubmissivelLayout);
        pnl_selecionarSubmissivelLayout.setHorizontalGroup(
            pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_selecionarSubmissivelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_selecionarSubmissivel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_selecionarSubmissivel)
                .addContainerGap())
        );
        pnl_selecionarSubmissivelLayout.setVerticalGroup(
            pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_selecionarSubmissivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_selecionarSubmissivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_selecionarSubmissivel)
                    .addComponent(cmb_selecionarSubmissivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_submissoesRetiradas.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de submissões retiradas"));
        pnl_submissoesRetiradas.setPreferredSize(new java.awt.Dimension(780, 127));

        jList_submissoesRetiradas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jList_submissoesRetiradas);

        javax.swing.GroupLayout pnl_submissoesRetiradasLayout = new javax.swing.GroupLayout(pnl_submissoesRetiradas);
        pnl_submissoesRetiradas.setLayout(pnl_submissoesRetiradasLayout);
        pnl_submissoesRetiradasLayout.setHorizontalGroup(
            pnl_submissoesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_submissoesRetiradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnl_submissoesRetiradasLayout.setVerticalGroup(
            pnl_submissoesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_submissoesRetiradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_selecionarSubmissivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_submissoesRetiradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_selecionarSubmissivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_submissoesRetiradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selecionarSubmissivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarSubmissivelActionPerformed
        this.cmb_selecionarSubmissivel.setEnabled(false);
        this.btn_selecionarSubmissivel.setEnabled(false);
        getRootPane().setDefaultButton(btn_cancelar);
    }//GEN-LAST:event_btn_selecionarSubmissivelActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_selecionarSubmissivel;
    private javax.swing.JComboBox cmb_selecionarSubmissivel;
    private javax.swing.JList jList_submissoesRetiradas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_selecionarSubmissivel;
    private javax.swing.JPanel pnl_submissoesRetiradas;
    // End of variables declaration//GEN-END:variables
}
